import * as dotenv from "dotenv";

export const MONGO_URI = "MONGO_URI";

export const PORT = "PORT";

export const NODE_ENV = "NODE_ENV";

export const JWT_EXPIRATION = "JWT_EXPIRES_IN";
export const JWT_ACCESS_SECRET = "JWT_ACCESS_SECRET_KEY";
export const JWT_REFRESH_SECRET = "JWT_REFRESH_SECRET_KEY";
export const JWT_PAYMENT_SECRET = "JWT_PAYMENT_SECRET_KEY";

export const SESSION_SECRET = "SESSION_SECRET";

export const REDIS_HOST = "REDIS_HOST";
export const REDIS_PASSWORD = "REDIS_PASSWORD";
export const REDIS_PORT = "REDIS_PORT";
export const REDIS_URL = "REDIS_URL";
export const DISABLE_REDIS = "DISABLE_REDIS";

export const TWILIO_ACCT = "TWILIO_ACCOUNT_SID";
export const TWILIO_TOKEN = "TWILIO_AUTH_TOKEN";
export const TWILIO_PHONE = "TWILIO_PHONE_NUMBER";

export const BLOCKRADAR_BASE_ID = "BLOCKRADAR_BASE_WALLET_ID";
export const BLOCKRADAR_BASE_SECRET = "BLOCKRADAR_BASE_WALLET_API_KEY";

export const BLOCKRADAR_ETH_ID = "BLOCKRADAR_ETH_WALLET_ID";
export const BLOCKRADAR_ETH_SECRET = "BLOCKRADAR_ETH_WALLET_API_KEY";

export const BLOCKRADAR_AVALANCHE_ID = "BLOCKRADAR_AVALANCHE_WALLET_ID";
export const BLOCKRADAR_AVALANCHE_SECRET =
  "BLOCKRADAR_AVALANCHE_WALLET_API_KEY";

export const BLOCKRADAR_GLOBAL_API_KEY = "BLOCKRADAR_GLOBAL_KEY";

export const PAYSTACK_SECRET = "PAYSTACK_SECRET";

export const YC_API_KEY = "YC_API_KEY";
export const YC_SECRET_KEY = "YC_SECRET_KEY";

export const ETH_SEPOLIA_RPC_URL = "ETH_SEPOLIA_RPC_URL";
export const BASE_SEPOLIA_RPC_URL = "BASE_SEPOLIA_RPC_URL";

export const ALCHEMY_AUTH_TOKEN = "ALCHEMY_AUTH_TOKEN";
export const ALCHEMY_BASE_SIGNING_KEY = "ALCHEMY_BASE_SIGNING_KEY";
export const ALCHEMY_ETH_SIGNING_KEY = "ALCHEMY_ETH_SIGNING_KEY";
export const ALCHEMY_ETH_WEBHOOK_ID = "ALCHEMY_ETH_WEBHOOK_ID";
export const ALCHEMY_BASE_WEBHOOK_ID = "ALCHEMY_BASE_WEBHOOK_ID";
export const ALCHEMY_USE_MAINNET = "USE_MAINNET";

export const MAILJET_API_KEY = "EMAIL_API_KEY";
export const MAILJET_SECRET_KEY = "EMAIL_SECRET_KEY";

export const CORS_WHITELIST_URLS = "CORS_WHITELIST_URLS";

export const WHATSAPP_VERIFY_TOKEN = "WHATSAPP_VERIFY_TOKEN";
export const WHATSAPP_ACCESS_TOKEN = "WHATSAPP_ACCESS_TOKEN";
export const WHATSAPP_BUSINESS_ACCOUNT_ID = "WHATSAPP_BUSINESS_ACCOUNT_ID";
export const WHATSAPP_APP_SECRET = "WHATSAPP_APP_SECRET";
export const WHATSAPP_PHONE_ID = "WHATSAPP_PHONE_ID";

// Ensure these important env credentials exists else fail before the server loads up
dotenv.config();
[
  MONGO_URI,
  PORT,
  JWT_EXPIRATION,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  JWT_PAYMENT_SECRET,
  SESSION_SECRET,
  TWILIO_ACCT,
  TWILIO_TOKEN,
  TWILIO_PHONE,
  BLOCKRADAR_BASE_ID,
  BLOCKRADAR_BASE_SECRET,
  BLOCKRADAR_ETH_ID,
  BLOCKRADAR_ETH_SECRET,
  BLOCKRADAR_AVALANCHE_ID,
  BLOCKRADAR_AVALANCHE_SECRET,
  PAYSTACK_SECRET,
  YC_API_KEY,
  YC_SECRET_KEY,
  BLOCKRADAR_GLOBAL_API_KEY,
  ETH_SEPOLIA_RPC_URL,
  BASE_SEPOLIA_RPC_URL,
  ALCHEMY_AUTH_TOKEN,
  ALCHEMY_BASE_SIGNING_KEY,
  ALCHEMY_ETH_SIGNING_KEY,
  ALCHEMY_ETH_WEBHOOK_ID,
  ALCHEMY_BASE_WEBHOOK_ID,
  MAILJET_API_KEY,
  MAILJET_SECRET_KEY,
  CORS_WHITELIST_URLS,
  ALCHEMY_USE_MAINNET,
  WHATSAPP_VERIFY_TOKEN,
  WHATSAPP_ACCESS_TOKEN,
  WHATSAPP_BUSINESS_ACCOUNT_ID,
  WHATSAPP_APP_SECRET,
  WHATSAPP_PHONE_ID,
].forEach((key) => {
  const value = process.env[key];
  if (!value) throw new Error(`config error - missing env.${key}`);
});

// Conditionally require Redis envs only if Redis is enabled
const redisDisabled = process.env[DISABLE_REDIS] === "true";
if (!redisDisabled) {
  [REDIS_HOST, REDIS_PASSWORD, REDIS_PORT, REDIS_URL].forEach((key) => {
    const value = process.env[key];
    if (!value) throw new Error(`config error - missing env.${key}`);
  });
}
